export const AUTH_ERRORS = {
  INVALID_EMAIL: 'AUTH_INVALID_EMAIL',
  OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  INVALID_OTP: 'AUTH_INVALID_OTP',
  TOO_MANY_REQUESTS: 'AUTH_TOO_MANY_REQUESTS',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  INVALID_SESSION: 'AUTH_INVALID_SESSION',
  DEVICE_REVOKED: 'AUTH_DEVICE_REVOKED',
  UNAUTHORIZED_DEVICE: 'AUTH_UNAUTHORIZED_DEVICE',
  INVALID_GOOGLE_TOKEN: 'AUTH_INVALID_GOOGLE_TOKEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export const OTP_CONFIG = {
  EXPIRATION_MINUTES: 5,
  LENGTH: 6,
  MAX_ATTEMPTS_PER_WINDOW: 3,
  RATE_LIMIT_WINDOW_MINUTES: 15,
} as const;

export const SESSION_CONFIG = {
  TOKEN_EXPIRATION_DAYS: 30,
} as const;
